### ISSUE TITLE
Problema ao buscar dados meteorológicos

### ISSUE THREAD

**Issue by seederk** [ocfgaldino/inmetpy#30]
Ao realizar o comando
inmet.get_data_station("2021-01-01", "2021-02-01", "day", ["A225"]) 

recebo a seguinte mensagem:
Requesting data for station A225 from 2021-01-01 to 2021-02-01.
⛅️  Request error: Request status 404
END 
No data for the whole period for stations: "A225"

Já testei para diversas estações e recebo sempre o mesmo retorno, mesmo as que existem sim dados para aquele periodo.

**Comment by ocfgaldino** [comment]
Olá @seederk ! Obrigado pelo feedback.

Realmente os dados não estão sendo mais disponibilizados através da API que eu usei para criar o pacote. Após a sua mensagem ,eu baixei o pacote em um ambiente novo e realmente nenhum endpoint da API está funcional (Erro 404). Fui ao site do INMET para verificar se houve mudança nos endpoints e na maneira em que as consultas são realizadas.  No site oficial do INMET há um comunicado na parte do manual da API, que não esclarece o que ou porque removeram a API, mas aparentemente ela não está mais no ar nem disponível para consultas. 

Entrarei em contato com eles para entender o que houve e se há previsão de retorno, e se será da mesma maneira que antes. Até lá, o pacote acaba se tornando obsoleto. 

Se retornarem a API, irei readequar o pacote para ele poder ser utilizado normalmente, e com uma documentação melhor. 

Muito obrigado pelo aviso, não sabia desse problema até ler a sua issue. Irei fechar está issue pois o problema já está esclarecido.
